CREATE TABLE ROBOTS (
	ID NUMBER(2),
	NOMBRE VARCHAR2(50) NOT NULL,
	TIPO VARCHAR2(50) NOT NULL,
	ESTADO VARCHAR2(50) NOT NULL,
	CONSTRAINT pk_robot PRIMARY KEY (ID)
);

CREATE TABLE USUARIOS (
    IDENTIFICADOR NUMBER(10),
    NOMBRE VARCHAR2(100) NOT NULL,
    TIPO VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_usuario PRIMARY KEY (IDENTIFICADOR)
);

CREATE TABLE TABLEROS (
    IDENTIFICADOR NUMBER(10),
    POSICIONES VARCHAR2(255) NOT NULL,
    CONSTRAINT pk_tablero PRIMARY KEY (IDENTIFICADOR)
);

CREATE TABLE COMPONENTES (
    IDENTIFICADOR NUMBER(10),
    ID_ROBOT NUMBER(2),
    CONSTRAINT pk_componente PRIMARY KEY (IDENTIFICADOR),
    CONSTRAINT fk_comp_robot FOREIGN KEY (ID_ROBOT) REFERENCES ROBOTS(ID)
);

CREATE TABLE OCUPADOS (
    ID_TABLERO NUMBER(10),
    IDENTIFICADOR NUMBER(10),
    ESTADO VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_ocupado PRIMARY KEY (ID_TABLERO, IDENTIFICADOR),
    CONSTRAINT fk_ocupado_tablero FOREIGN KEY (ID_TABLERO) 
        REFERENCES TABLEROS(IDENTIFICADOR) ON DELETE CASCADE
);

CREATE TABLE COMANDOS (
    IDENTIFICADOR NUMBER(10),
    NOMBRE_ACCION VARCHAR2(100) NOT NULL,
    VALOR NUMBER(10, 2),
    ID_ROBOT NUMBER(2) NOT NULL, -- Relación con ROBOTS
    CONSTRAINT pk_comando PRIMARY KEY (IDENTIFICADOR),
    CONSTRAINT fk_comando_robot FOREIGN KEY (ID_ROBOT) REFERENCES ROBOTS(ID)
);

CREATE TABLE SENSORES (
    ID_COMPONENTE NUMBER(10),
    TIPO VARCHAR2(50) NOT NULL,
    ESTADO VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_sensor PRIMARY KEY (ID_COMPONENTE),
    CONSTRAINT fk_sensor_padre FOREIGN KEY (ID_COMPONENTE) REFERENCES COMPONENTES(IDENTIFICADOR)
);

CREATE TABLE CINTAS (
    ID_COMPONENTE NUMBER(10),
    VELOCIDAD NUMBER(5, 2),
    DIRECCION VARCHAR2(50) NOT NULL,
    ESTADO VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_cinta PRIMARY KEY (ID_COMPONENTE),
    CONSTRAINT fk_cinta_padre FOREIGN KEY (ID_COMPONENTE) REFERENCES COMPONENTES(IDENTIFICADOR)
);

CREATE TABLE PINZAS (
    ID_COMPONENTE NUMBER(10),
    ESTADO VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_pinza PRIMARY KEY (ID_COMPONENTE),
    CONSTRAINT fk_pinza_padre FOREIGN KEY (ID_COMPONENTE) REFERENCES COMPONENTES(IDENTIFICADOR)
);

CREATE TABLE PIEZAS (
    COD_PIEZA NUMBER(10),
    TIPO VARCHAR2(50) NOT NULL,
    ID_SENSOR NUMBER(10) NOT NULL,
    CONSTRAINT pk_pieza PRIMARY KEY (COD_PIEZA),
    CONSTRAINT fk_pieza_sensor FOREIGN KEY (ID_SENSOR) REFERENCES SENSORES(ID_COMPONENTE)
);

